language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction

script: vendor/bin/phpunit tests/

matrix:
  allow_failures:
    - php: hhvm
