language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS hsa_notes;'

before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate:install --no-interaction -vvv

script:
  - php artisan migrate:reset --force --no-interaction -vvv
  - php artisan migrate --force --no-interaction -vvv
  - php artisan db:seed --force --no-interaction -vvv
  - vendor/bin/phpunit tests/

matrix:
  allow_failures:
    - php: hhvm
